# Generated by Django 3.0.6 on 2021-03-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tron4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitcounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelcount', models.IntegerField()),
            ],
        ),
    ]
